version: '3.8'

services:
  web:
    build: .
    env_file:
      # use .env file to hold postgres info
      - .env
    ports:
      - "8080:3000"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    # where do we want to persist this data
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
